name: Multi-Env CI/CD

on:
  push:
    branches: [dev, uat, main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          # Add your test command here
          echo "Run tests here"

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - run: echo "Deploying to DEV environment"

  create-pr-to-uat:
    if: github.ref == 'refs/heads/dev'
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request to UAT
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: uat
          branch: dev-pr-to-uat/${{ github.sha }}
          title: 'Promote changes from dev to uat'
          body: 'Automated PR to promote changes from dev to uat after successful workflow.'
          delete-branch: true

  deploy-uat:
    if: github.ref == 'refs/heads/uat'
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - run: echo "Deploying to UAT environment"

  create-pr-to-prod:
    if: github.ref == 'refs/heads/uat'
    needs: deploy-uat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request to PROD
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: uat-pr-to-main/${{ github.sha }}
          title: 'Promote changes from uat to main'
          body: 'Automated PR to promote changes from uat to main after successful workflow.'
          delete-branch: true

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - run: echo "Deploying to PROD environment"
