name: Multi-Env CI/CD

on:
  push:
    branches: [dev, uat, main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          # Add your test command here
          echo "Run tests here"

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - run: echo "Deploying to DEV environment"

  deploy-uat:
    if: github.ref == 'refs/heads/uat'
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - run: echo "Deploying to UAT environment"

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - run: echo "Deploying to PROD environment"
